### PR TITLE
bug: permission issues when overwriting domains_color_file

### PR DESCRIPTION
**Pull request by currocam**
As explained in this [issue]( https://github.com/medema-group/BiG-SCAPE/issues/22), there are problems with Singularity because the code tries to overwrite the source file. 

This is fine if the user has write permissions on that file (as I understand, in the Docker image and Singularity, if you use the --writable argument). However, I think there are better solutions than this (especially when integrating the program into a pipeline). 

It is unclear how the code works: is it necessary to overwrite this file? Could you use temporary files? Although I do not have much knowledge, I would say that the program's current behavior (being able to edit a tsv file persistently) could be achieved by creating a "configuration" file in the user's home folder rather than overwriting the source code of the program. I have attached a PR with an initial proposal.

### CODE REVIEW

**Review by currocam — COMMENTED** [review]
Instead of overwriting the source file, copy it into user's home directory

**Comment by pur80a** [comment]
I encountered the same issue as in #22, but in a centrally installed conda environment. 
This is how I installed it: 
```
VERSION=1.1.5
conda env create --name bigscape-$VERSION --file https://raw.githubusercontent.com/medema-group/BiG-SCAPE/v${VERSION}/bigscape_dependencies.yml
conda activate bigscape-$VERSION
mkdir -p ${CONDA_PREFIX}/share
pushd ${CONDA_PREFIX}/share
git clone --quiet --depth 1 --branch v$VERSION $URL
chmod +x BiG-SCAPE/bigscape.py
pushd ${CONDA_PREFIX}/bin/
ln -s ../share/BiG-SCAPE/bigscape.py bigscape.py
# resolve bug
# https://github.com/medema-group/BiG-SCAPE/issues/22
# https://stackoverflow.com/a/44853818/17440360
cp $CONDA_PREFIX/share/BiG-SCAPE/ArrowerSVG.py $CONDA_PREFIX/share/BiG-SCAPE/ArrowerSVG.py.bkp
grep -A8 -n " if len(new_color_domains)" $CONDA_PREFIX/share/BiG-SCAPE/ArrowerSVG.py | sed -e 's/[^0-9].*$//' -e 's/$/s|^|#|/' | sed -f- -i $CONDA_PREFIX/share/BiG-SCAPE/ArrowerSVG.py
popd; popd
```
I agree with @currocam that not editing the source code, but writing to a new file, would be advantages.

**Comment by adraismawur** [comment]
Hello! Thanks for the contribution and sorry it took us so long to address this. I have opened a new pull request which should resolve this issue by copying the colors file into the output directory instead. I'd prefer not to put anything in the users' home directory.

**Comment by jowodo** [comment]
Looking forward to the next release :)

**Pull request closed without merging**
